name: clinician
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auth0_flutter: 
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  auto_size_text: ^3.0.0
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.4.0

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/